# Atom Linter plugin - https://atom.io/packages/linter-sass-lint
# Sass Lint rules - https://github.com/sasstools/sass-lint/tree/master/docs/rules
files:
  include:
    - 'lib/**/*.scss'
    - 'src/**/*.scss'
  ignore:
    - 'node_modules'
rules:
  attribute-quotes: 2
  border-zero:
    - 2
    -
      convention: 0
  brace-style:
    - 2
    -
      style: '1tbs'
      allow-single-line: false
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  hex-length:
    - 2
    -
      style: 'short'
  hex-notation:
    - 2
    -
      style: 'lowercase'
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: true
  max-file-line-count:
    - 1
    -
      length: 200
  max-line-length:
    - 1
    -
      length: 120
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  mixins-before-declarations:
    - 2
    -
      exclude:
        - 'breakpoint'
        - 'mq'
  nesting-depth:
    - 1
    -
      max-depth: 3
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 1
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 1
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  property-sort-order: 1
  pseudo-element: 2
  quotes:
    - 2
    -
      style: 'single'
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
  space-before-colon: 0
  space-between-parens: 0
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  zero-unit: 2
